name = "wiley eats"
description = "wiley's hypercritical food blog"
license = "MIT"
min_version = "0.13.0"

[original]
author =  "Chester How"
homepage = "https://chesterhow.github.io/tale/"
repo = "https://github.com/chesterhow/tale"
